[package]
name = "public-appservice"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
ruma = { version = "0.11.1", features = ["appservice-api", "client-hyper-native-tls", "client-api-c", "client-ext-client-api"] }
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
toml = "0.8.19"
